#############################################################################################################
# .circleci/config.yml                                                                                      #
#                                                                                                           #
# by: Kevin Imber <kvimber@gmail.com>                                                                       #
# on: Thu, Jun 1st, 2023                                                                                    #
#                                                                                                           #
# Mostly a copy from                                                                                        #
#   https://github.com/circleci/tests-plugin-cli/blob/CVL-305/poc-running-failed-tests/.circleci/config.yml #
#############################################################################################################
version: 2.1

orbs:
  docker: circleci/docker@2.0.5
  python: circleci/python@2.1.1

parameters:
  go-version:
    type: string
    default: "1.18"

commands:
  setup:
    steps:
      - checkout:
          path: project
      - run:
          command: go mod download
          working_directory: project
      - run:
          command: ./do install-devtools
          working_directory: project

workflows:
  build-test-deploy:
    jobs:
      - pytest-run:
          context:
            - dockerhub-readonly
      # - pytest-run-all-tests:
      #     context:
      #       - dockerhub-readonly
      #         # - pytest-run-failed-tests-only:
      #         #     context:
      #         #       - dockerhub-readonly

jobs:
  pytest-run:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          name: install pip
          command: |
            set -e -x
            sudo apt --allow-unauthenticated --allow-downgrades --allow-remove-essential --allow-change-held-packages install python3-pip
            pip3 install --upgrade pip
      - run:
          name: setup pytest
          command: pip3 install -r requirements.txt
      - run:
          name: run all tests
          command: pytest


  pytest-run-all-tests:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          name: install pip
          command: sudo apt --allow-unauthenticated --allow-downgrades --allow-remove-essential --allow-change-held-packages install python3-pip
      - run:
          name: setup pytest
          command: pip3 install -r requirements.txt
      - run:
          name: run all tests
          command: |
            set -e -x
            TEST_FILES=$(circleci tests glob "tests/**/[0-9]*.py" | circleci tests split)
            echo "test files:"
            echo $TEST_FILES
            # pytest --collect-only -q | --command="xargs pytest --junitxml=./results/test-results.xml--"
            pytest $TEST_FILES
      - store_test_results:
          path: ./results/test-results.xml

  pytest-run-failed-tests-only:
    machine:
      image: ubuntu-2204:2023.04.2
    steps:
      - checkout
      - run:
          name: install pip
          command: sudo apt --allow-unauthenticated --allow-downgrades --allow-remove-essential --allow-change-held-packages install python3-pip
      - run:
          name: setup pytest
          command: pip3 install -r requirements.txt
      - run:
          name: run failed tests only
          command: pytest --collect-only -q | RERUN_FAILED=1 RUNNER=pytest go run main.go  --command="xargs pytest --junitxml=./results/test-results.xml --"
      - store_test_results:
          path: ./results/test-results.xml

